
authorList=[]
titleList = []
venueList=[]
volumeList=[]
pagesList = []
yearList = []
keyList = []
typeList=[]
accessList=[]
keyList=[]
doiList = []
eeList = []
urlList = []
csvNames=["author","title","venue","volume",'pages',"year",'type',"access","key",'doi',"ee","url"]