# Generated by Django 3.2.12 on 2022-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField()),
                ('itemImage', models.CharField(max_length=120)),
                ('userImage', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('rating', models.CharField(max_length=120)),
                ('itemName', models.CharField(max_length=120)),
                ('itemType', models.CharField(max_length=120)),
                ('itemSize', models.CharField(max_length=120)),
                ('itemBrand', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
