# Generated by Django 3.2.12 on 2022-03-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemBrand',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemImage',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemSize',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='userImage',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='username',
            field=models.CharField(max_length=256),
        ),
    ]
