# Generated by Django 4.0.3 on 2022-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20220322_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemBrand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemType',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemSize',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemName',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemId',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
