# Generated by Django 4.0.3 on 2022-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_itembrand_item_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=256)),
                ('userImage', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
