# Generated by Django 4.0.3 on 2022-04-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userImage',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
