# Generated by Django 3.2.12 on 2022-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20220512_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(choices=[('$10', '10'), ('$20', '20'), ('$30', '30'), ('$40', '40')], default=20),
        ),
    ]
