# Generated by Django 3.2.12 on 2022-05-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20220513_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(choices=[('$10', 10), ('$20', 20), ('$30', 30), ('$40', 40)], default=20),
        ),
    ]
