# Generated by Django 3.2.12 on 2022-05-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(choices=[('$10', '10'), ('$20', '20'), ('$30', '30'), ('$40', '40')], default=20),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1', to='items.item')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match2', to='items.item')),
            ],
        ),
    ]
